### ISSUE TITLE
Let transports fail gracefully

### ISSUE THREAD

**Issue by rumpelsepp** [Fraunhofer-AISEC/gallia#153]
If e.g. a non existent can interface is specified, `gallia` fails because `dumpcap` fails with a non zero exit code. The reason for this is that `dumpcap` is called before `load_transport()`

**Comment by rumpelsepp** [comment]
This case must be handled better.

```
$ gallia scan uds identifiers --target "foobar"
```

**Comment by rumpelsepp** [comment]
That's currently not so bad any more:

```
$ uv run -- gallia scan uds identifiers --target "foobar"
Oct 17 10:29:09.841 gallia.command.base: Artifacts base folder not defined, no artifacts will be saved!
Oct 17 10:29:09.842 gallia.command.base: '' is not a valid TransportScheme
Traceback (most recent call last):
  File "/home/steff/Projects/work/gallia/src/gallia/command/base.py", line 330, in entry_point
    exit_code = await self.run()
                ^^^^^^^^^^^^^^^^
  File "/home/steff/Projects/work/gallia/src/gallia/command/base.py", line 409, in run
    await self.setup()
  File "/home/steff/Projects/work/gallia/src/gallia/command/uds.py", line 128, in setup
    await super().setup()
  File "/home/steff/Projects/work/gallia/src/gallia/command/base.py", line 506, in setup
    self.transport = load_transport(self.config.target)
                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/steff/Projects/work/gallia/src/gallia/plugins/plugin.py", line 78, in load_transport
    if target.scheme == transport.SCHEME:
       ^^^^^^^^^^^^^
  File "/home/steff/Projects/work/gallia/src/gallia/transports/base.py", line 53, in scheme
    return TransportScheme(self.url.scheme)
  File "/home/steff/.local/share/uv/python/cpython-3.14.0rc2-linux-x86_64-gnu/lib/python3.14/enum.py", line 707, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/steff/.local/share/uv/python/cpython-3.14.0rc2-linux-x86_64-gnu/lib/python3.14/enum.py", line 1192, in __new__
    raise ve_exc
ValueError: '' is not a valid TransportScheme
```
